STRINGS = {
    "convert_title": "格式转换",
    "convert_subtitle": "先保留统一入口，后续可继续扩展到 COCO / LabelMe / VOC / DOTA",
    "convert_card": "转换参数",
    "convert_card_sub": "当前已支持 VOC XML -> YOLO，其他格式将逐步补全",
    "input_mode": "输入模式",
    "source_format": "源格式",
    "target_format": "目标格式",
    "input_path": "输入文件/文件夹",
    "output_path": "输出文件夹",
    "classes_file": "类别文件",
    "save_classes": "保存类别路径",
    "run_convert": "开始转换",
    "clear_log": "清空日志",
    "log_title": "运行日志",
    "browse": "浏览",
    "single_file": "单文件",
    "batch_folder": "批量目录",
    "preview_mode": "预览模式",
    "preview_run": "预览结果",
    "apply_run": "应用并落盘",
    "convert_missing_input": "请输入有效输入路径",
    "convert_unsupported": "当前组合尚未实现",
    "replace_title": "类别重整",
    "replace_subtitle": "单类替换、多类合并、删除、重排序、按新 classes.txt 自动重映射",
    "replace_preview": "预览",
}

